### ISSUE TITLE
About Dynamo Player thumbnail

### ISSUE THREAD

**Issue by lillismith** [johnpierson/DynamoPlayerSamples#3]
could we try an informational icon here?  like a simple i in a circle?  maybe there is a standard for this Helena?

**Comment by johnpierson** [comment]
Oh, also for reference I tend to use these for my own development. 
https://materialdesignicons.com/

If we were wanting to go more "icon-y" approach that is good to know. To me, the word "image" did not mean icon I guess.

![image](https://user-images.githubusercontent.com/15744724/142496658-1960ffcf-c127-49b7-83d7-ccd25f83bc11.png)

**Comment by lillismith** [comment]
![information-outline](https://user-images.githubusercontent.com/2932690/142497637-9c95ad84-b29f-4097-9eac-33589e020f26.png)
